var filmList = {
    "Dune": 
        {
             "names":["Dune", "Cồn Cát"],
             "title":"Review phim Dune (2021): Mới lạ nhưng chỉ mới là bắt đầu",
             "images":{"img-main":"images/film-main-images/Dune-2021-xu-cat-.jpeg",
                       "img-poster":"",
                       "img-danh-gia":"https://ghienreview.com/wp-content/uploads/2021/10/Ghien-review-Dune-2021-Xu-cat-min-2048x1180.jpg", 
                       "img-1":"https://ghienreview.com/wp-content/uploads/2021/10/Ghien-review-Dune-2021-Xu-cat-04-min-scaled-e1634835550934.jpg", 
                       "img-2":"https://ghienreview.com/wp-content/uploads/2021/10/Ghien-review-Dune-2021-Xu-cat-03.jpg", 
                       "img-3":"https://ghienreview.com/wp-content/uploads/2021/10/Ghien-review-Dune-2021-Xu-cat-02-min.jpg"
                      },
             "info":{"thoi-luong":"155 phút",
                     "dao-dien":["Denis Villeneuve"],
                     "dien-vien":["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac"],
                     "quoc-gia":["Mỹ"], 
                     "the-loai":["Hành động", "Kịch tính", "Phiêu lưu", "Viễn tưởng"],
                     "khoi-chieu":"18/10/2021"
                    },
             "description":"Dune (tựa tiếng Việt: Xứ cát) là một trong những siêu phẩm khoa học viễn tưởng được mong chờ bậc nhất năm 2021. Vốn được chuyển thể từ tiểu thuyết cùng tên lên màn ảnh rộng rất nhiều lần nhưng chưa hề có một bộ phim Dune nào đạt được thành công như nội dung gốc của nó. Đơn giản bởi vì cốt truyện của Dune cực kỳ phức tạp với nhiều phe phái, khái niệm và chứa đựng nhiều thứ khá là dị, vượt xa ra khỏi trí tưởng tượng của chúng ta. Với việc quy tụ dàn diễn viên hạng A Hollywood cùng với sự lèo lái của vị đạo diễn đã mang đến thành công cho Blade Runner 2049 hay siêu phẩm gây sốc Incendies (2010) – Denis Villeneuve, khán giả rất mong đợi phiên bản 2021 của Dune sẽ đem lại vinh quang cho thương hiệu này. Hãy cùng Ghiền review phim Dune (2021) để xem thử liệu rằng phim có hấp dẫn và đáng xem không các bạn nhé!",
             "story":{"story-text-1":["Lấy bối cảnh trong tương lai xa, Dune (2021) là câu chuyện kể về Paul Atreides – con trai của người đứng đầu gia tộc Atreides hùng mạnh thuộc đế chế Imperium. Một ngày nọ, hoàng đế có chiếu chỉ điều động gia tộc này đến tiếp quản hành tinh sa mạc Arrakis và khai thác loại sản vật Spice độc nhất cực kỳ đắt giá của nơi đây. Tuy nhiên, đây chỉ là một nước đi trong bàn cờ chính trị đầy thâm hiểm và vô hình trung đẩy Paul bước đi trên hành trình định mệnh với sức mạnh to lớn tiềm ẩn bên trong con người cậu. Xem phim để cùng Paul khám phá ra những điều mới mẻ đang chờ ở phía trước nha."], 
                        "story-text-2":["Nhìn chung, Dune (2021) là một bộ phim cực kỳ hoành tráng với nhiều khung cảnh hùng vĩ, mới lạ kèm theo những thứ vô cùng khác biệt, thậm chí là dị hợm nhưng lại tạo ra được sự tò mò thích thú cho người xem. Phim đã rất thành công khi đặt những viên gạch đầu tiên để xây nên nền móng vững chắc cho vũ trụ viễn tưởng này và tạo ra nhiều chất liệu tiềm năng để các nhà biên kịch phát triển trong tương lai. Tuy nhiên về tổng thể nội dung, cốt truyện và cách dẫn dắt thì phim vẫn thiếu đi sự hấp dẫn và đặc sắc cần có, từ đó khiến phim trở nên lê thê, dài dòng và mang đến cảm giác nhàm chán xen lẫn khó hiểu cho khán giả. Hãy cùng Ghiền review tìm hiểu sâu hơn về những điểm cộng và điểm trừ của phim nhé."]
                        },
                "trailer-youtube-iframe":'<iframe width="100%" height="768" src="https://www.youtube.com/embed/R797Sf-2zt0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                "positive":{"positive-text-1":["Nhìn chung, Dune (2021) là một bộ phim cực kỳ hoành tráng với nhiều khung cảnh hùng vĩ, mới lạ kèm theo những thứ vô cùng khác biệt, thậm chí là dị hợm nhưng lại tạo ra được sự tò mò thích thú cho người xem. Phim đã rất thành công khi đặt những viên gạch đầu tiên để xây nên nền móng vững chắc cho vũ trụ viễn tưởng này và tạo ra nhiều chất liệu tiềm năng để các nhà biên kịch phát triển trong tương lai. Tuy nhiên về tổng thể nội dung, cốt truyện và cách dẫn dắt thì phim vẫn thiếu đi sự hấp dẫn và đặc sắc cần có, từ đó khiến phim trở nên lê thê, dài dòng và mang đến cảm giác nhàm chán xen lẫn khó hiểu cho khán giả. Hãy cùng Ghiền review tìm hiểu sâu hơn về những điểm cộng và điểm trừ của phim nhé."],
                                "positive-text-2":["Âm thanh và hình ảnh của Dune (2021) chính là một trong những điểm cộng to bự của bộ phim khoa học viễn tưởng này. Với tài năng của Hans Zimmer, thật sự không có gì để bàn cãi về sự xuất sắc của phần nhạc phim. Sự ma mị, nguy hiểm những cũng đầy bi tráng trong từng nốt trầm khi vang lên, quả thực khiến người nghe muốn nổi da gà. Đáng tiếc là bối cảnh và nội dung phim còn thiếu độ vĩ mô để tương xứng với quả nhạc chất lượng được viết riêng cho Dune. Bên cạnh đó, những góc quay và màu sắc của phim cũng được tính toán và xây dựng cực kỳ đẹp mắt, chân thực cũng như đậm chất nghệ thuật. Vì vậy nếu được thưởng thức tại rạp, chắc hẳn khán giả sẽ rất ấn tượng với phần nghe nhìn mà phim mang đến.",
                                                "Như đã nói ở trên, Dune (2021) quy tụ dàn sao cực kỳ chất lượng thuộc hàng top của Hollywood hiện tại với những cái tên uy tín như Timothée Chalamet, Oscar Isaac, Zendaya, Jason Momoa hay Josh Brolin. Trong đó nổi bật nhất vẫn là Timothée trong vai Paul và Rebecca Ferguson trong vai mẹ của nam chính. Cả hai đã có những phân cảnh thể hiện được khả năng biểu cảm đa dạng, đồng thời tính cách nhân vật của họ cũng được xây dựng rất đời thực, tự nhiên, vừa mạnh mẽ, thú vị nhưng cũng vừa đắn đo, bỡ ngờ như chính cảm xúc của khán giả khi trải qua những hành trình mới mẻ trong phim."]
                                },
                "negative":{"negative-text-1":["Trái với vẻ bên ngoài hào nhoáng cùng việc thiết lập nền tảng vững chắc cho những phần phim tiếp theo, nếu để ý kỹ, bạn sẽ thấy cốt truyện của Dune (2021) khá quá tải khi phải nhồi nhét quá nhiều thứ nhằm mục đích giúp khán giả làm quen với các phe phái, khả năng và khái niệm trong vũ trụ Dune. Chính vì vậy, phim thiếu đi tính cao trào cần có, thậm chí một trận chiến quy mô và mãn nhãn cũng không hề xuất hiện trong phim chắc hẳn sẽ khiến nhiều khán giả cảm thấy hụt hẫng. Đặc biệt cái kết của phim có phần hơi nhạt và kém ấn tượng có thể làm giảm điểm số mà người xem chấm cho bộ phim này."],
                                "negative-text-2":["Mọi thứ trên hành tinh cát nói riêng và vũ trụ Dune nói chung còn khá sơ sài, chưa được phác họa cụ thể nên chưa thể diễn tả được quy mô hoành tráng và phức tạp của thế giới trong phim. Sức mạnh của các nhân vật, sự xuất hiện của quái vật hay những phân cảnh chiến đấu cũng không tạo ra nhiều điểm nhấn do chúng quá giản đơn, thậm chí có thể đánh giá là qua loa, thiếu chiều sâu và đặc biệt không đáp ứng được kỳ vọng quá lớn của khán giả khi xem trailer.",
                                                "Yếu tố cảm xúc cũng được phim lướt qua quá nhanh khiến cho mọi thứ khó có thể đọng lại trong tâm trí người xem. Nhiều tình tiết trong Dune (2021) vẫn còn nặng tính sắp đặt, thiếu hợp lý và gây ra cảm giác khó hiểu cho khán giả. Bên cạnh đó, thông điệp mà phim muốn truyền tải cũng không thực rõ ràng, đồng thời plot twist mà phim xây dựng không quá mới mẻ, ít bất ngờ với nhịp phim không đồng đều, từ đó tạo ra một thử thách thực sự rất khó khăn cho việc kiên trì tập trung xem phim của khán giả.",
                                                "Mặc dù Dune (2021) có sự tham gia của nhiều diễn viên nổi tiếng nhưng nhân vật mà họ đảm nhận lại thiếu đất diễn, một màu và không được phát triển tính cách một cách hợp lý nên tất cả đều tỏ ra khá mờ nhạt và kém ấn tượng. Đặc biệt xem xong bộ phim này, khán giả sẽ có hàng trăm câu hỏi đặt ra trong đầu vì phim vẫn chưa giải thích hết các tình tiết và đặc điểm được nêu ra suốt gần 150 phút thời lượng phim. Do đó, trải nghiệm khi xem Dune thực sự không đến mức tuyệt vời như nhiều lời khen có cánh của báo giới quốc tế dành cho bộ phim khoa học viễn tưởng này."]
                        },
                "score":{"imdb":"8.3/10 (100.000 đánh giá)",
                        "google":"81/100", 
                        "rotten-tomatoes":"87/100 (cà chua tươi)",
                        "nml-review":"7/10 (Khá Ghiền)"
                        },
                "conclusion":"Dune (2021) đã mở ra một vũ trụ điện ảnh mới đầy tiềm năng và thú vị với nhiều hướng phát triển trong tương lai. Phim chứa đựng rất nhiều nội dung và phải thật tập trung cũng như kiên nhẫn thì bạn mới có thể hoàn thành được bộ phim có lối kể chuyện lê thê và thiếu điểm nhấn này. Hy vọng những phần tiếp theo, Dune sẽ không làm khán giả thất vọng với những cuộc phiêu lưu và trận chiến hấp dẫn, thú vị và đáng xem hơn!",
                "article-author-info":["Minh Chuyên Đi Copy Đây :v",
                                        "Còn bạn thì sao?"]
        },
    "Money-Heist-Season-5-2021": 
                {
                "names":["Money Heist", "Trộm tiền"],
                "title":"Review phim Money Heist season 5 phần 2: Kết hơi ảo nhưng cảm xúc",
                "images":{"img-main":"images/film-main-images/Money-Heist-Season-5.jpg",
                        "img-poster":"images/film-poster-images/money-heist-season-5-2021.jpg",
                        "img-danh-gia":"https://ghienreview.com/wp-content/uploads/2021/12/Ghien-review-Money-Heist-Season-5-phan-2-min-2048x1083.jpg", 
                        "img-1":"https://ghienreview.com/wp-content/uploads/2021/12/Ghien-review-Money-Heist-Season-5-phan-2-03.jpg", 
                        "img-2":"https://ghienreview.com/wp-content/uploads/2021/12/Ghien-review-Money-Heist-Season-5-phan-2-02.jpeg", 
                        "img-3":"https://ghienreview.com/wp-content/uploads/2021/12/Ghien-review-Money-Heist-Season-5-phan-2.jpg"
                        },
                "info":{"thoi-luong":"5 tập; 50 phút/tập",
                        "dao-dien":["Álex Pina"],
                        "dien-vien":["Úrsula Corberó", "Álvaro Morte", "Itziar Ituño"],
                        "quoc-gia":["Tây Ban Nha"], 
                        "the-loai":["Hành động", "Tội phạm", "Tâm lý"],
                        "khoi-chieu":"03/12/2021"
                        },
                "description":"Tháng cuối cùng của một năm đầy biến động 2021 đã đến rồi các bạn ạ. Đây cũng là tháng đánh dấu sự kết thúc của seri phim truyền hình ăn khách bậc nhất trên Netflix và có sức ảnh hưởng siêu lớn đến văn hóa đại chúng toàn cầu. Với 5 tập phim đầu của mùa 5, khán giả đã chứng kiến một trận đại chiến ác liệt giữa phe chính quyền và phe Giáo sư, liệu rằng 5 tập cuối của mùa này có thể gỡ hết những nút thắt mà phim đã tạo ra hay không? Hãy cùng Ghiền review phim Money Heist season 5 phần 2 để có câu trả lời các bạn nhé!",
                "story":{"story-text-1":["Sau cái chết của Tokyo, nhóm cướp mang mặt nạ Dali lại càng thêm quyết tâm để thực hiện thành công phi vụ hô biến 90 tấn vàng dữ trự của Tây Ban Nha. Tuy nhiên, biệt đội của Giáo sư không ngờ rằng họ đang bị quân của chính phủ lên kế hoạch để tấn công từ trong và ngoài nhằm bắt gọn cả băng nhóm và giải cứu con tin vô tội. Không những thế, kế hoạch của cả team còn bị những kẻ bí ẩn hớt tay trên đẩy họ vào hoàn cảnh đếm lịch đến mòn vân tay và rụng cả tóc. Kết thúc của Phi vụ triệu đô sẽ như thế nào? Xem phim để có câu trả lời các bạn nha."], 
                      "story-text-2":["Nhìn chung, 5 tập cuối của Money Heist season 5 quả thật mang đến cho người xem rất nhiều cảm xúc, đặc biệt là phim đã rất thành công trong khâu lựa chọn và sử dụng âm nhạc để đẩy cao trào và tạo ấn tượng trong lòng khán giả. Các tập phim có tình tiết cuốn hút, hấp dẫn người xem và gợi nhớ đến các nhân vật đã gắn bó với seri này. Tuy nhiên phim vẫn mắc rất nhiều lỗi logic và chưa giải quyết thỏa đáng, ngọn ngành mọi vấn đề nên để lại cảm giác lấn cấn và chưa thực sự thỏa mãn cho người xem. Hãy cùng phân tích kỹ hơn về những điểm mạnh và điểm yếu để có cái nhìn tổng quan hơn về phim các bạn nhé!"]
                     },
                "trailer-youtube-iframe":'<iframe width="100%" height="768" src="https://www.youtube.com/embed/R797Sf-2zt0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                "positive":{"positive-text-1":["Theo Ghiền review, điểm cộng lớn nhất của Money Heist season 5 phần 2 chính là việc tạo được sự hấp dẫn trong các tình tiết, đặc biệt là ở những phân cảnh cuối cùng của mỗi tập, từ đó gây ra sự tò mò và cảm giác muốn xem ngay tập tiếp theo. Nếu như Money Heist season 5 phần 1 tập trung vào các cảnh chiến đấu thì phần 2 đã quay về với hướng đi khiến phim trở nên nổi tiếng như hiện nay – tập trung vào sự đấu trí và chỉn chu trong các kế hoạch của Giáo sư. Nhờ vậy 5 tập cuối của mùa 5 có vẻ mang lại nhiều cảm xúc và sự hứng thú hơn cho khán giả khi theo dõi."],
                                "positive-text-2":["Cảm xúc của phim còn được xây dựng nhờ phần nghe và phần nhìn siêu đỉnh của Money Heist season 5 phần 2. Ghiền review cực kỳ bất ngờ vì sự nâng cấp rất lớn ở phần hình ảnh và âm thanh của phim. Những góc quay và sự phối trộn màu sắc của Phi vụ triệu đô mùa 5 cực kỳ đẹp mắt và chạm đến ngưỡng nghệ thuật dù đôi lúc hơi bị lạm dụng slow motion khiến phim không khác gì được sản xuất ở Ấn Độ. Đặc biệt phần âm nhạc của phần này đã đa dạng và phù hợp với mạch phim và hình ảnh hơn, từ đó đẩy cảm xúc lên rất tốt và mang đến cảm giác trải nghiệm điện ảnh thực sự cho người xem, nhất là khi ca khúc Bella Ciao vang lên.",
                                                "Diễn xuất luôn là điểm mà thương hiệu Money Heist làm rất tốt và điều này tiếp tục được phát huy ở season 5 phần 2. Trải qua một thời gian dài gắn bó với nhân vật của mình, các diễn viên dù chính hay phụ đều có được sự tự nhiên, chân thực và thần thái tuyệt vời khi thể hiện vai diễn. Nhờ vậy mà khi theo dõi, khán giả luôn cảm thấy thoải mái, đồng cảm và đặc biệt là càng yêu mến các nhân vật hơn. Chắc hẳn với mùa cuối cùng của seri này, khán giả sẽ lại càng tiếc nuối và nhớ hơn về những con người đã làm nên thương hiệu văn hóa toàn cầu này.", 
                                                "Thông điệp mà 5 tập cuối của mùa 5 truyền tải không qua rõ ràng và ấn tượng vì bản chất phim cũng đang ca ngợi về những phản anh hùng, làm đẹp hơn hình ảnh của những tên cướp trong mắt khán giả. Tuy nhiên có thể thấy Money Heist season 5 phần 2 muốn nhấn mạnh về niềm tin, vai trò của người đứng đầu, sự chân thật, tình yêu, tình bạn, tình cảm gia đình, danh dự, những âm mưu mang tầm quốc gia và đặc biệt là khuyên người xem hãy làm mọi thứ hết mình để nhận về những thứ tốt đẹp và xứng đáng với bản thân."]
                                },
                "negative":{"negative-text-1":["Mặc dù có rất nhiều điểm cộng nhưng phải thừa nhận rằng cái kết của Money Heist season 5 phần 2 vẫn để lại nhiều lấn cấn trong lòng người xem. Dễ thấy nhất chính là việc 5 tập cuối có rất nhiều tình tiết vô lý, nặng tính sắp đặt và mọi thứ hơi bị đơn giản quá mức. Cách mà Giáo sư và team trốn thoát thực sự không thuyết phục được những khán giả khó tính vì mọi thứ trên thực tế sẽ không đơn giản như phim. Tuy nhiên nhìn một cách rộng ra thì đó là lối thoát hợp lý duy nhất mà các biên kịch có thể nghĩ ra để gỡ bỏ những nút thắt siêu khó được đặt ra từ mùa 3.", 
                                                "Tính cách, suy nghĩ và thái độ của một số nhân vật trong Money Heist season 5 phần thay đổi một cách chóng mặt, gây ra nhiều tranh cãi nơi khán giả. Đơn cử như cách xây dựng nhân vật nữ thanh tra Alicia với siêu năng lực vừa sinh con đã có thể cho Giáo sư vào tròng và trốn thoát khỏi vòng vây cảnh sát. Khoan bàn về khả năng đặc biệt này thì khán giả cũng cảm thấy khó chấp nhận việc nhân vật lúc thì thù ghét nhưng ngay sau đó lại là bạn, thậm chí là có tình cảm với người lãnh đạo băng cướp. Ngoài ra, phim có nhiều cảnh flashback hơi thừa thãi và quá tập trung vào nhân vật Berlin cũng phần nào gây ra sự lan man và làm loãng nội dung chính của Phi vụ triệu đô."],
                                "negative-text-2":[]
                                },
                "score":{"imdb":"8.3/10 (370.000 đánh giá)",
                        "google":"97/100", 
                        "rotten-tomatoes":"100/100",
                        "nml-review":"8/10 (Ghiền)"
                        },
                "conclusion":"Money Heist season 5 phần 2 là một cái kết trọn vẹn nhưng chưa xuất sắc của loạt phim trộm cướp thành công bậc nhất lịch sử điện ảnh này. Những tập cuối cùng này đã khai thác tốt yếu tố cảm xúc thông qua việc nâng tầm chất lượng hình ảnh, âm thanh và đặc biệt tập trung vào sự thú vị trong các kế hoạch của Giáo sư và băng cướp. Mặc dù phim vẫn còn mắc nhiều lỗi về logic và không thực sự làm thỏa mãn và thuyết phục người xem nhưng trải nghiệm mà Phi vụ triệu đô mang đến thực sự rất đáng giá. Chắc hẳn người ta sẽ còn nhắc đến nhiều về bộ phim này khi phiên bản Hàn Quốc và phần ngoại truyện về nhân vật Berlin được lên sóng trong thời gian tới.",
                "article-author-info":["Minh Chuyên Đi Copy Đây :v",
                                        "Còn bạn, bạn đánh giá phim này như thế nào?"]
                }

}

                