var filmList = {
    "Dune": {"names":["Dune", "Cồn Cát"],
             "images":{"img-main":"",
                       "img-poster":"",
                       "img-danh-gia":"", 
                       "img-1":"", 
                       "img-2":"", 
                       "img3":""
                      },
             "info":{"thoi-luong":"",
                     "dao-dien":"",
                     "dien-vien":["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac"],
                     "quoc-gia":"Mỹ", 
                     "the-loai":["Hành động", "Kịch tính", "Phiêu lưu", "Viễn tưởng"],
                     "khoi-chieu":"18/10/2021"
                    },
             "description":"Dune (tựa tiếng Việt: Xứ cát) là một trong những siêu phẩm khoa học viễn tưởng được mong chờ bậc nhất năm 2021. Vốn được chuyển thể từ tiểu thuyết cùng tên lên màn ảnh rộng rất nhiều lần nhưng chưa hề có một bộ phim Dune nào đạt được thành công như nội dung gốc của nó. Đơn giản bởi vì cốt truyện của Dune cực kỳ phức tạp với nhiều phe phái, khái niệm và chứa đựng nhiều thứ khá là dị, vượt xa ra khỏi trí tưởng tượng của chúng ta. Với việc quy tụ dàn diễn viên hạng A Hollywood cùng với sự lèo lái của vị đạo diễn đã mang đến thành công cho Blade Runner 2049 hay siêu phẩm gây sốc Incendies (2010) – Denis Villeneuve, khán giả rất mong đợi phiên bản 2021 của Dune sẽ đem lại vinh quang cho thương hiệu này. Hãy cùng Ghiền review phim Dune (2021) để xem thử liệu rằng phim có hấp dẫn và đáng xem không các bạn nhé!",
             "story":{"story-text-1":"Lấy bối cảnh trong tương lai xa, Dune (2021) là câu chuyện kể về Paul Atreides – con trai của người đứng đầu gia tộc Atreides hùng mạnh thuộc đế chế Imperium. Một ngày nọ, hoàng đế có chiếu chỉ điều động gia tộc này đến tiếp quản hành tinh sa mạc Arrakis và khai thác loại sản vật Spice độc nhất cực kỳ đắt giá của nơi đây. Tuy nhiên, đây chỉ là một nước đi trong bàn cờ chính trị đầy thâm hiểm và vô hình trung đẩy Paul bước đi trên hành trình định mệnh với sức mạnh to lớn tiềm ẩn bên trong con người cậu. Xem phim để cùng Paul khám phá ra những điều mới mẻ đang chờ ở phía trước nha.", 
                      "story-text-2":"Nhìn chung, Dune (2021) là một bộ phim cực kỳ hoành tráng với nhiều khung cảnh hùng vĩ, mới lạ kèm theo những thứ vô cùng khác biệt, thậm chí là dị hợm nhưng lại tạo ra được sự tò mò thích thú cho người xem. Phim đã rất thành công khi đặt những viên gạch đầu tiên để xây nên nền móng vững chắc cho vũ trụ viễn tưởng này và tạo ra nhiều chất liệu tiềm năng để các nhà biên kịch phát triển trong tương lai. Tuy nhiên về tổng thể nội dung, cốt truyện và cách dẫn dắt thì phim vẫn thiếu đi sự hấp dẫn và đặc sắc cần có, từ đó khiến phim trở nên lê thê, dài dòng và mang đến cảm giác nhàm chán xen lẫn khó hiểu cho khán giả. Hãy cùng Ghiền review tìm hiểu sâu hơn về những điểm cộng và điểm trừ của phim nhé."
                     },
             "positive:":{"positive-text-1":"Nhìn chung, Dune (2021) là một bộ phim cực kỳ hoành tráng với nhiều khung cảnh hùng vĩ, mới lạ kèm theo những thứ vô cùng khác biệt, thậm chí là dị hợm nhưng lại tạo ra được sự tò mò thích thú cho người xem. Phim đã rất thành công khi đặt những viên gạch đầu tiên để xây nên nền móng vững chắc cho vũ trụ viễn tưởng này và tạo ra nhiều chất liệu tiềm năng để các nhà biên kịch phát triển trong tương lai. Tuy nhiên về tổng thể nội dung, cốt truyện và cách dẫn dắt thì phim vẫn thiếu đi sự hấp dẫn và đặc sắc cần có, từ đó khiến phim trở nên lê thê, dài dòng và mang đến cảm giác nhàm chán xen lẫn khó hiểu cho khán giả. Hãy cùng Ghiền review tìm hiểu sâu hơn về những điểm cộng và điểm trừ của phim nhé.",
                          "positive-text-2":["Âm thanh và hình ảnh của Dune (2021) chính là một trong những điểm cộng to bự của bộ phim khoa học viễn tưởng này. Với tài năng của Hans Zimmer, thật sự không có gì để bàn cãi về sự xuất sắc của phần nhạc phim. Sự ma mị, nguy hiểm những cũng đầy bi tráng trong từng nốt trầm khi vang lên, quả thực khiến người nghe muốn nổi da gà. Đáng tiếc là bối cảnh và nội dung phim còn thiếu độ vĩ mô để tương xứng với quả nhạc chất lượng được viết riêng cho Dune. Bên cạnh đó, những góc quay và màu sắc của phim cũng được tính toán và xây dựng cực kỳ đẹp mắt, chân thực cũng như đậm chất nghệ thuật. Vì vậy nếu được thưởng thức tại rạp, chắc hẳn khán giả sẽ rất ấn tượng với phần nghe nhìn mà phim mang đến.",
                                             "Như đã nói ở trên, Dune (2021) quy tụ dàn sao cực kỳ chất lượng thuộc hàng top của Hollywood hiện tại với những cái tên uy tín như Timothée Chalamet, Oscar Isaac, Zendaya, Jason Momoa hay Josh Brolin. Trong đó nổi bật nhất vẫn là Timothée trong vai Paul và Rebecca Ferguson trong vai mẹ của nam chính. Cả hai đã có những phân cảnh thể hiện được khả năng biểu cảm đa dạng, đồng thời tính cách nhân vật của họ cũng được xây dựng rất đời thực, tự nhiên, vừa mạnh mẽ, thú vị nhưng cũng vừa đắn đo, bỡ ngờ như chính cảm xúc của khán giả khi trải qua những hành trình mới mẻ trong phim."]
                         },
             "negative":{"negative-text-1":"Trái với vẻ bên ngoài hào nhoáng cùng việc thiết lập nền tảng vững chắc cho những phần phim tiếp theo, nếu để ý kỹ, bạn sẽ thấy cốt truyện của Dune (2021) khá quá tải khi phải nhồi nhét quá nhiều thứ nhằm mục đích giúp khán giả làm quen với các phe phái, khả năng và khái niệm trong vũ trụ Dune. Chính vì vậy, phim thiếu đi tính cao trào cần có, thậm chí một trận chiến quy mô và mãn nhãn cũng không hề xuất hiện trong phim chắc hẳn sẽ khiến nhiều khán giả cảm thấy hụt hẫng. Đặc biệt cái kết của phim có phần hơi nhạt và kém ấn tượng có thể làm giảm điểm số mà người xem chấm cho bộ phim này.",
                         "negative-text-2":["Mọi thứ trên hành tinh cát nói riêng và vũ trụ Dune nói chung còn khá sơ sài, chưa được phác họa cụ thể nên chưa thể diễn tả được quy mô hoành tráng và phức tạp của thế giới trong phim. Sức mạnh của các nhân vật, sự xuất hiện của quái vật hay những phân cảnh chiến đấu cũng không tạo ra nhiều điểm nhấn do chúng quá giản đơn, thậm chí có thể đánh giá là qua loa, thiếu chiều sâu và đặc biệt không đáp ứng được kỳ vọng quá lớn của khán giả khi xem trailer.",
                                            "Yếu tố cảm xúc cũng được phim lướt qua quá nhanh khiến cho mọi thứ khó có thể đọng lại trong tâm trí người xem. Nhiều tình tiết trong Dune (2021) vẫn còn nặng tính sắp đặt, thiếu hợp lý và gây ra cảm giác khó hiểu cho khán giả. Bên cạnh đó, thông điệp mà phim muốn truyền tải cũng không thực rõ ràng, đồng thời plot twist mà phim xây dựng không quá mới mẻ, ít bất ngờ với nhịp phim không đồng đều, từ đó tạo ra một thử thách thực sự rất khó khăn cho việc kiên trì tập trung xem phim của khán giả.",
                                            "Mặc dù Dune (2021) có sự tham gia của nhiều diễn viên nổi tiếng nhưng nhân vật mà họ đảm nhận lại thiếu đất diễn, một màu và không được phát triển tính cách một cách hợp lý nên tất cả đều tỏ ra khá mờ nhạt và kém ấn tượng. Đặc biệt xem xong bộ phim này, khán giả sẽ có hàng trăm câu hỏi đặt ra trong đầu vì phim vẫn chưa giải thích hết các tình tiết và đặc điểm được nêu ra suốt gần 150 phút thời lượng phim. Do đó, trải nghiệm khi xem Dune thực sự không đến mức tuyệt vời như nhiều lời khen có cánh của báo giới quốc tế dành cho bộ phim khoa học viễn tưởng này."]
                        },
             "score":{"imdb":"8.3/10 (100.000 đánh giá)",
                      "google":"81/100", 
                      "rotten-tomatoes":"87/100 (cà chua tươi)",
                      "nml-review":"7/10 (Khá Ghiền)"
                     },
             "conclusion":"Dune (2021) đã mở ra một vũ trụ điện ảnh mới đầy tiềm năng và thú vị với nhiều hướng phát triển trong tương lai. Phim chứa đựng rất nhiều nội dung và phải thật tập trung cũng như kiên nhẫn thì bạn mới có thể hoàn thành được bộ phim có lối kể chuyện lê thê và thiếu điểm nhấn này. Hy vọng những phần tiếp theo, Dune sẽ không làm khán giả thất vọng với những cuộc phiêu lưu và trận chiến hấp dẫn, thú vị và đáng xem hơn!",
             "article-author-info":["Minh Chuyên Đi Copy Đây :v",
                                    "Còn bạn thì sao?"]
            }
}